update-interval: 10
debug: true
custom-names:
 minecraft:forest: "Лес"
minecraft:flower_forest: "Цветочный лес"
minecraft:birch_forest: "Берёзовый лес"
minecraft:dark_forest: "Тёмный лес"
minecraft:old_growth_birch_forest: "Старый берёзовый лес"
minecraft:old_growth_spruce_taiga: "Старая еловая тайга"
minecraft:plains: "Равнины"
minecraft:sunflower_plains: "Подсолнуховые равнины"
minecraft:savanna: "Саванна"
minecraft:savanna_plateau: "Саванное плато"
minecraft:mountains: "Горы"
minecraft:gravelly_mountains: "Гравийные горы"
minecraft:windswept_hills: "Продуваемые ветром холмы"
minecraft:windswept_forest: "Продуваемый ветром лес"
minecraft:windswept_gravelly_hills: "Продуваемые ветром гравийные холмы"
minecraft:taiga: "Тайга"
minecraft:snowy_taiga: "Снежная тайга"
minecraft:old_growth_pine_taiga: "Старая сосновая тайга"
minecraft:old_growth_spruce_forest: "Старый еловый лес"
minecraft:swamp: "Болото"
minecraft:mangrove_swamp: "Мангровое болото"
minecraft:desert: "Пустыня"
minecraft:badlands: "Бэдлендс"
minecraft:wooded_badlands: "Лесистый бэдлендс"
minecraft:eroded_badlands: "Размытый бэдлендс"
minecraft:jungle: "Джунгли"
minecraft:bamboo_jungle: "Бамбуковые джунгли"
minecraft:sparse_jungle: "Редкие джунгли"
minecraft:ocean: "Океан"
minecraft:deep_ocean: "Глубокий океан"
minecraft:frozen_ocean: "Замёрзший океан"
minecraft:cold_ocean: "Холодный океан"
minecraft:warm_ocean: "Тёплый океан"
minecraft:lukewarm_ocean: "Умеренный океан"
minecraft:river: "Река"
minecraft:frozen_river: "Замёрзшая река"
minecraft:beach: "Пляж"
minecraft:snowy_beach: "Снежный пляж"
minecraft:snowy_plains: "Снежные равнины"
minecraft:ice_spikes: "Ледяные шипы"
minecraft:frozen_peaks: "Замёрзшие пики"
minecraft:jagged_peaks: "Зубчатые пики"
minecraft:snowy_slopes: "Снежные склоны"
minecraft:lush_caves: "Пышные пещеры"
minecraft:deep_dark: "Глубокая тьма"
minecraft:nether_wastes: "Незерские пустоши"
minecraft:crimson_forest: "Багровый лес"
minecraft:warped_forest: "Искажённый лес"
minecraft:basalt_deltas: "Базальтовые дельты"
minecraft:the_end: "Энд"
minecraft:end_midlands: "Средние земли Энда"
minecraft:end_barrens: "Пустоши Энда"
minecraft:small_end_islands: "Малые острова Энда"
world-settings:
  world:
    enabled: true
  world_nether:
    enabled: true
  world_the_end:
    enabled: true